import React from "react";
import { Link } from "gatsby";
import "./index.sass";
import Layout from "../components/layout";
import CurrencyBox from "../components/CurrencyBox";
import icoUser1 from "../resources/ico-user-level-1.svg";
import icoUser2 from "../resources/ico-user-level-2.svg";
import icoUser3 from "../resources/ico-user-level-3.svg";
import icoTriangle from "../resources/ico-triangle.svg";
import icoShield from "../resources/ico-shield.svg";
import icoEye from "../resources/ico-eye.svg";
import icoPlay from "../resources/ico-play.svg";
import Modal from "../components/Modal";
import Player from "@vimeo/player";

const bottomLabelTx = "Q4 2018";
const currencies = [
	{ nCurrency: "nUSD", currency: "USD", currencyNumber: "$1.00" },
	{ nCurrency: "nEUR", currency: "EURO", currencyNumber: "€1.00", bottomLabel: bottomLabelTx },
	{ nCurrency: "nJPY", currency: "YEN", currencyNumber: "¥1.00", bottomLabel: bottomLabelTx },
	{ nCurrency: "nAUD", currency: "AUD", currencyNumber: "$1.00", bottomLabel: bottomLabelTx },
	{ nCurrency: "nKRW", currency: "WON", currencyNumber: "₩1.00", bottomLabel: bottomLabelTx },
	{ nCurrency: "nXAU", currency: "ounce/gold", currencyNumber: "1.00", bottomLabel: bottomLabelTx }
];

class IndexPage extends React.Component {
	state = {
		isOpen: false
	};

	player = null;

	startVideo() {
		this.player = new Player("video-how-it-works", {
			id: 254987969,
			width: 640
		});

		this.player.play();
	}

	pauseVideo() {
		if (this.player) this.player.pause();
	}

	render() {
		let { isOpen } = this.state;
		return (
			<Layout>
				<div className="home-page">
					<section className="section pb-30">
						<div className="container">
							<h1 className="page-title">Powering payments for dApps</h1>
							<div className="page-subtitle">
								Havven enables stable, censorship resistant payments for dApps in multiple
								currencies. Our stablecoins are backed by a network of eighty thousand token holders
								around the world.
							</div>

							<div className="columns is-centered main-buttons">
								<div className="column is-narrow has-text-centered">
									<a
										href="javascript:void(0)"
										className="is-button is-subtle-alt is-blue main-button"
										onClick={() => {
											this.setState({ isOpen: true });
											this.startVideo();
										}}
									>
										<img src={icoPlay} className="is-icon" alt="Intro" /> Intro
									</a>
								</div>
								<div className="column is-narrow has-text-centered">
									<Link to="/contact-us" className="is-button is-simple main-button">
										Contact Us
									</Link>
								</div>
							</div>
							<div className="has-text-centered pb-10">
								<Link to="/eosio" className="is-button is-announcement">
									<span>NEW</span>
									<span>Havven launching on EOSIO</span>
								</Link>
							</div>
						</div>
					</section>
					<section className="section currency-section pb-110 pt-30">
						<div className="container">
							<div className="columns is-centered currency-row">
								{currencies.slice(0, 3).map(el => (
									<CurrencyBox {...el} key={el.currency} />
								))}
							</div>
							<div className="columns is-centered currency-row pb-110">
								{currencies.slice(3).map(el => (
									<CurrencyBox {...el} key={el.currency} />
								))}
							</div>
						</div>

						<div className="section-title">
							Havven provides a multicurrency suite of stablecoins.
						</div>
						<div className="section-desc">
							Our stablecoin, nomins, are currently available in nUSD with nEUR, nJPY, nKRW, nAUD,
							nXAU, and more coming in the near future!
						</div>
					</section>
					<section className="section is-padded">
						<div className="section-title is-white is-narrow pb-50">
							Havven is built for engineers
						</div>
						<CodeBox />
						<div className="has-text-centered">
							<a
								href="https://developer.havven.io/"
								target="_blank"
								className="is-button is-blue is-wide is-subtle"
							>
								View our Developer Portal
							</a>
						</div>
					</section>
					<section className="section is-white is-padded pb-110">
						<div className="section-title is-large">Get rewarded for maintaining stability</div>
						<div className="section-desc pb-70">
							HAV holders who mint nomins are entitled to receive fees generated by nomin
							transactions.
						</div>
						<div className="columns is-centered get-rewarded-boxes">
							<a className="column" href="https://dashboard.havven.io/" target="_blank">
								<div className="c-top">
									<img src={icoUser2} alt="For new and experienced users" />
									<div className="p1 red">
										For New and <br /> Experienced Users
									</div>
								</div>
								<div className="c-bottom">
									<div className="p2 red">Dashboard</div>
									<div className="p3">An overview of the Havven network</div>
								</div>
							</a>
							<a className="column" href="https://swappr.io/" target="_blank">
								<div className="c-top">
									<img src={icoUser1} alt="For new users" />
									<div className="p1 blue">For New Users</div>
								</div>
								<div className="c-bottom">
									<div className="p2 blue">Swappr</div>
									<div className="p3">Easily swap ETH for HAV and nUSD</div>
								</div>
							</a>
							<a className="column" href="https://mintr.havven.io/" target="_blank">
								<div className="c-top">
									<img src={icoUser3} alt="For experienced users" />
									<div className="p1 green">For Experienced Users</div>
								</div>
								<div className="c-bottom">
									<div className="p2 green">Mintr</div>
									<div className="p3">Mint nUSD and collect fees</div>
								</div>
							</a>
						</div>
					</section>
					<section className="section is-grey is-padded">
						<div className="section-title">Our network is decentralised</div>
						<div className="section-desc mb-80">
							The Havven payment network is designed to be decentralised and trustless.
						</div>
						<div className="columns is-centered feature-boxes">
							<div className="column">
								<div className="c-img">
									<img src={icoTriangle} alt="Trustless" />
								</div>
								<div className="p1">Trustless</div>
								<div className="p2">
									A distributed pool of token holders are responsible for maintaining stability.
								</div>
							</div>
							<div className="column">
								<div className="c-img">
									<img src={icoShield} alt="Censorship resistant" />
								</div>
								<div className="p1">Censorship Resistant</div>
								<div className="p2">
									Collateral is provided by individual HAV holders, which means it can’t be seized.
								</div>
							</div>
							<div className="column">
								<div className="c-img">
									<img src={icoEye} alt="Transparent" />
								</div>
								<div className="p1">Transparent</div>
								<div className="p2">
									Our collateral is on-chain so doesn’t require pesky third party audits.
								</div>
							</div>
						</div>
					</section>
				</div>
				<Modal
					isOpen={isOpen}
					onRequestClose={() => {
						this.setState({ isOpen: false });
						this.pauseVideo();
					}}
					className="is-video"
				>
					<div data-vimeo-id="254987969" data-vimeo-width="840" id="video-how-it-works" />
				</Modal>
			</Layout>
		);
	}
}

export default IndexPage;

const CodeBox = () => (
	<div className="ui-box is-code code-regular mb-50">
		<span className="code-comment">
			{"//"} Initialize havven-js library with any signer (Metamsak, Trezor, Ledger, PrivateKey
			supported)
		</span>
		<br />
		<span className="code-green">const </span>
		{"{"} HavvenJs {"}"} = <span className="code-green">require</span>(
		<span className="code-white">'havven-js'</span>
		);
		<br />
		<span className="code-green">const </span> metaMaskSigner ={" "}
		<span className="code-green">new</span> HavvenJs.signers.Metamask();
		<br />
		<span className="code-green">const </span> havjs = new HavvenJs(
		{"{"}
		signer: metaMaskSigner
		{"}"}
		);
		<br />
		<br />
		<span className="code-comment">
			{"//"} Transfer stablecoins to any ethereum address, wallet or smart contract
		</span>
		<br />
		<span className="code-green">const </span>
		txObj = <span className="code-green">await</span> havjs
		<br />
		&nbsp;&nbsp;&nbsp;.StablePayments
		<br />
		&nbsp;&nbsp;&nbsp;.transfer(
		<span className="code-white">'0x5C545CA7f9D34857664FDCe6aDC22edcF1D5061f'</span>,<br />
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;havjs.util.parseEther(
		<span className="code-white">'100'</span>
		));
	</div>
);
