import React from "react";
import { graphql, withPrefix } from "gatsby";
import "./index.sass";
import Layout from "../components/layout";
import "./tokens.sass";
import TokenBox from "../components/TokenBox";
import joinDiscordButton from "../resources/products/join-discord.svg";

const TokensPage = ({ data }) => {
	let tokens = data && data.allFile && data.allFile.edges[0].node.childPagesJson.tokens;
	let otherTokens = tokens && tokens.slice(1, tokens.length);
	return (
		<Layout>
			<div className="tokens-page">
				<section className="section header-section">
					<div className="container">
						<h1 className="page-title">
							Contract information about the tokens within the Synthetix Network
						</h1>
					</div>
				</section>
				<section className="section is-white minting-synths">
					{tokens ? (
						<div className="container">
							<TokenBox
								title={tokens[0].symbol}
								tokens={[tokens[0]]}
								description="Gets staked as collateral to back Synths and entitles stakers to receive fees generated by Synth trades on Synthetix.Exchange."
							></TokenBox>
							<TokenBox title="Synth" tokens={otherTokens} />
						</div>
					) : null}
				</section>
				<div className="section is-white discord">
					<a
						class="discord-button"
						href={"https://discordapp.com/invite/AEdUHzt"}
						target="_blank"
					>
						<img src={joinDiscordButton} />
					</a>
				</div>
			</div>
		</Layout>
	);
};

export const query = graphql`
	query TokensPageQuery {
		site {
			siteMetadata {
				discordUrl
			}
		}
		allFile(filter: { absolutePath: { regex: "/(pages)/tokens.json$/" } }) {
			edges {
				node {
					childPagesJson {
						tokens {
							symbol
							address
							decimals
							description
						}
					}
				}
			}
		}
	}
`;

export default TokensPage;
