import React from "react";
import { graphql, withPrefix } from "gatsby";
import "../index.sass";
import Layout from "../../components/layout";
import "./mintr.sass";
import mintrLogo from "../../resources/products/mintr.svg";
import mintrButton from "../../resources/products/mintr-button.svg";
import joinDiscordButton from "../../resources/products/join-discord.svg";
import collatRatio from "../../resources/collat-ratio.svg";
import stepOne from "../../resources/1.svg";
import stepTwo from "../../resources/2.svg";
import stepThree from "../../resources/3.svg";
import mint from "../../resources/mint.svg";
import burn from "../../resources/burn.svg";
import claim from "../../resources/claim.svg";

const MintrPage = props => {
	const { mintrUrl, discordUrl } = props.data.site.siteMetadata;
	let mintrScreenshot = withPrefix(`/img/mintr_v2_screenshot.png`);
	return (
		<Layout>
			<div className="mintr-page">
				<section className="section header-section"></section>
				<section className="section mintr-about">
					<div className="columns is-centered mintr-columns">
						<div className="column">
							<div className="icon-img">
								<img src={mint}></img>
							</div>
							<div className="p1">Mint Synths</div>
							<div className="p2">by locking up SNX collateral</div>
						</div>
						<div className="column">
							<div className="icon-img">
								<img src={burn}></img>
							</div>
							<div className="p1">Burn Synths</div>
							<div className="p2">to unlock SNX</div>
						</div>
						<div className="column">
							<div className="icon-img">
								<img src={claim}></img>
							</div>
							<div className="p1">Claim fees</div>
							<div className="p2">from the Synthetix Network</div>
						</div>
					</div>
					<div className="product-desc">
						Mintr is a dApp for SNX holders to perform a variety of actions in the
						Synthetix Network. It provides a clean and intuitive interface that allows
						users to mint and burn Synths, manage their collateralisation ratio, collect
						fees generated by circulating Synths, send sUSD to a selling queue, view
						their balances and Mintr history, unlock escrowed SNX, and more.
					</div>
				</section>
				<a
					className="purple-button centered"
					href="https://mintr.synthetix.io"
					target="_blank"
				>
					Visit the dApp
				</a>
				<section className="section how-it-works">
					<div className="section-title is-white sp5">How it works</div>
					<div className="steps is-centered how-steps">
						<div className="column">
							<div className="number-img">
								<img src={stepOne}></img>
							</div>
							<div className="p1">
								Connect a wallet (e.g. MetaMask, Trezor) containing SNX tokens
							</div>
						</div>
						<div className="column">
							<div className="number-img">
								<img src={stepTwo}></img>
							</div>
							<div className="p1">
								Click “Mint” and decide how much sUSD you would like to mint
							</div>
						</div>
						<div className="column">
							<div className="number-img">
								<img src={stepThree}></img>
							</div>
							<div className="p1">
								Use your new sUSD to trade, or stake SNX, to claim weekly rewards
							</div>
						</div>
					</div>
				</section>
				<section className="section collat-ratio">
					<div className="container">
						<div className="section-title is-white sp5 pb-40">
							Minting Synths and the Collateralisation Ratio
						</div>
						<div className="section-image">
							<img src={collatRatio}></img>
						</div>
						<div className="section-desc is-white sp4">
							Synthetix allows synthetic assets (Synths) to be minted against the
							value of SNX tokens. This is done by locking SNX into a smart contract
							as collateral at a ratio of 750% to the Synths minted. For example, this
							means that if 1000 SNX is locked at a value of $0.10 USD, 13.3 sUSD can
							be minted against it. 750% has been chosen to provide ample protection
							against price fluctuations.
							<br />
							<br />
							Your Collateralisation Ratio affects the proportion you receive of fees
							generated by Synth transactions. If your Ratio drops below 750%, you
							will not be able to claim fees until you have brought it back above
							750%. This is to incentivise SNX holders from maintaining the entire
							Network Collateralisation Ratio (i.e. value of total locked SNX against
							value of total Synths) as well as keeping Synth prices stable.
						</div>
					</div>
				</section>
				<section className="section discord">
					<a class="discord-button" href={discordUrl} target="_blank">
						<img src={joinDiscordButton} />
					</a>
				</section>
			</div>
		</Layout>
	);
};
export const query = graphql`
	query MintrPageQuery {
		site {
			siteMetadata {
				mintrUrl
				discordUrl
			}
		}
	}
`;

export default MintrPage;
